#ifndef _SCANNER_H
#define _SCANNER_H

#include <stdio.h>
#include "loc.h"

#define MaxIdentLen 31    // Maximum length for identifiers
#include <stdbool.h>

#define false 0
#define true 1
  
/* Typedef: TokenType enum
 * This enumeration defines the constants for the different token types.
 * The scanner should return these values for the associated key words
 * and token types.  The numbers start at 256 because 0-255 are reserved
 * for single character token values. After pp1, we will rely on
 * y.tab.h generated by yacc for these constants.
 */
#define TOK(x) x
typedef enum { 
    T_Void = 256,
    T_LessEqual, T_GreaterEqual, T_Equal, T_NotEqual, T_And, T_Or,
    T_While, T_For, T_If, T_Else, 
    T_Identifier, T_StringConstant, T_IntConstant, T_BoolConstant, 
	T_Include, T_Section, T_Global, T_DataByte, T_Equ, T_Dollar,
	T_Comment, T_Org, T_Lda, T_Sta,
	TOK(T_Mfi),
	TOK(T_Add),
	TOK(T_Sub),
	TOK(T_Inc),
	TOK(T_Jmp),
	TOK(T_Jz),
	TOK(T_Jnz),
	TOK(T_Js),
	TOK(T_Jns),
	TOK(T_Jc),
	TOK(T_Jnc),
	T_End,
    T_NumTokenTypes
} TokenType;

#undef TOK
#define TOK(x) #x

/* These are a list of printable names for each token value defined
 * above.  The strings should match in position to the types. They
 * are used in our main program to verify output from your scanner.
 */

static const char *gTokenNames[T_NumTokenTypes] = {
  "T_Void",
  "T_LessEqual", "T_GreaterEqual", "T_Equal", "T_NotEqual",
  "T_And", "T_Or", "T_While", "T_For", "T_If", "T_Else",
  "T_Identifier", "T_StringConstant", "T_IntConstant", "T_BoolConstant",
  "T_Include", "T_Section", "T_Global", "T_DataByte", "T_Equ", "T_Dollar",
  "T_Comment", "T_Org", "T_Lda", "T_Sda",
  TOK(T_Mfi),
  TOK(T_Add), 
  TOK(T_Sub),
  TOK(T_Inc),
  TOK(T_Jmp),
  TOK(T_Jz),
  TOK(T_Jnz),
  TOK(T_Js),
  TOK(T_Jns),
  TOK(T_Jc),
  TOK(T_Jnc),
  "T_End"
};

 
/* Typedef: YYSTYPE
 * Defines the union type that is used by the scanner to store
 * attibute information about tokens as they are scanned. This
 * type definition will be generated by Yacc in the later assignments.
 */
typedef union {
    int integerConstant;
    bool boolConstant;
    char *stringConstant;
    char identifier[MaxIdentLen+1]; // +1 for terminating null
} YYSTYPE;

 
/* Global variable: yylval
 * Strange name, but by convention, this is the name of union that
 * is written to by scanner and read by parser containing information
 * about the lexeme just scanned.
 */
extern YYSTYPE yylval;

extern char *yytext;      // Text of lexeme just scanned

#ifdef __cplusplus
extern "C" {
#endif

int yylex();              // Defined in the generated lex.yy.c file

void InitScanner();                 // Defined in scanner.l user subroutines

#ifdef __cplusplus
}
#endif


#endif
